import '../../styles/common.css'
import '../../ripple/ripple.css'
import '../../badge/badge.css'
import '../../icon/icon.css'
import '../bottomNavigationItem.css'
import '../BottomNavigationItemSfc.css'
